@AlphaApi_BaseAddress = http://localhost:5223/api/alpha

GET {{AlphaApi_BaseAddress}}/13
Accept: application/json

###

POST {{AlphaApi_BaseAddress}}
Content-Type: application/json

{
  "Name": "ENTITY001"
}

###